netdisco/netdisco

Netdisco/Changes
Netdisco/lib/App/Netdisco/Manual/Vendors.pod

tested by jvi and seems to work okay

Add documentation note about SNMPv3 configuration on Cisco IOS

---

.travis.yml
Netdisco/Makefile.PL

This small Makefile.PL change and .travis.yml file have Netdisco building and testing in Travis CI.

Add Travis CI support

---

lib/App/Netdisco/Worker/Plugin/Discover/Neighbors.pm

fix neighbors discover

---

lib/App/Netdisco/SSHCollector/Platform/PaloAlto.pm

The PAN CLI tries to do friendly auto-completion things and makes the SSH
Collector fail sporadically.  This change uses the "set cli scripting-mode on"
command to calm down the PAN CLI and works around the extra echoed prompts that
get sent.
This change also adds collection of IPv6 neighbor information.
I'm not entirely happy with how I handle the CLI interactions.  Rancid's `panlogin` looks like a good template for how to handle prompts but I got stumped trying to convert tcl expect to perl Expect.
This is tested against PAN-OS 8.  I don't have any other PAN-OS versions to test against, unfortunately.

Improve Palo Alto SSH Collector support

---

lib/App/Netdisco/DB/ResultSet/NodeIp.pm
lib/App/Netdisco/Worker/Plugin/MakeRancidConf.pm

Hi @ollyg 
Please review the PR.
https://cpants.cpanauthors.org/release/OLIVER/App-Netdisco-2.039033
Many Thanks.
Best Regards,
Mohammad S Anwar

Fixed pod error as reported by CPANTS.

---

share/config.yml

disclaimer: i did not test this is any way, came across it when looking for something else.

remove double define of "plugin:"

---

share/public/javascripts/portsort.js

i'm not in anyway versed in javascript, but this hack fixes #457 for me.

workaround for #457

---

share/views/ajax/device/ports.tt

if i'm reading the code correctly that is....

i think end anchor should be in the if/end clause

---

Build.PL
lib/App/Netdisco/Worker/Plugin/Discover/Neighbors/Routed.pm

Add IS-IS support. Needs SNMP::Info to also support IS-IS. 
fixes #546

Add IS-IS Support

---

bin/netdisco-do

All to indicate the "-d" parameters multiple time to perform an action on many host with only one command call.

Modification of netdisco-do 

---

.gitignore
MANIFEST.SKIP

having a go at intellij + perl support & cygwin. working surprisingly well.
exclude it's project configuration

intellij exclusion support

---

lib/App/Netdisco/DB/Result/Admin.pm
lib/App/Netdisco/DB/Result/DeviceModule.pm
lib/App/Netdisco/DB/Result/DevicePortSsid.pm
lib/App/Netdisco/DB/Result/DevicePortWireless.pm
lib/App/Netdisco/DB/Result/DevicePower.pm
lib/App/Netdisco/DB/Result/Log.pm
lib/App/Netdisco/DB/Result/NodeMonitor.pm
lib/App/Netdisco/DB/Result/Oui.pm
lib/App/Netdisco/DB/Result/Process.pm
lib/App/Netdisco/DB/Result/Session.pm
lib/App/Netdisco/DB/Result/Subnet.pm
lib/App/Netdisco/DB/Result/UserLog.pm

since the rest was removed, these comments no longer make sense

last pieces of b59043d / #590

---

share/views/ajax/device/ports.tt
share/views/ajax/search/port.tt
share/views/sidebar/device/ports.tt

The port free icon currently only differs from the port down icon by colour, on higher resolutions with a colour vision impairment they're not very distinguishable, a slightly different icon fixes this.

Change Port Free icon to be more accessible

---

lib/App/Netdisco/Web/Auth/Provider/DBIC.pm

Lines 110-112 commented out
Lines 113-124 added
Lines 233-249 added match_with_radius  function

Modified to add Radius support

---

lib/App/Netdisco/Web/Auth/Provider/DBIC.pm

fix raidus typo

---

lib/App/Netdisco/Web/Plugin/Inventory.pm
lib/App/Netdisco/Web/Search.pm
share/views/ajax/search/device.tt
share/views/layouts/main.tt

sort the os_ver in the web interface

---

lib/App/Netdisco/SSHCollector/Platform/NXOS.pm

* $ssh->capture() aka. directly executing a command via
ssh <device> <command> does not seem to work on NXOS7, maybe
also others
* changed this module to use Expect, successfully tested on
NXOS6 - NXOS9

Change SSHCollector::NXOS to use expect

---

lib/App/Netdisco/Web/Plugin/Report/IpInventory.pm
share/views/ajax/report/ipinventory.tt
share/views/ajax/report/ipinventory_csv.tt

* request on mailing list by Adrian Sevcenco, 08.04.20,
"[Netdisco] how to modify report: add column to ip inventory"
* I think there is no harm in adding this generally to the report, but let me know if you think otherwise

Add vendor to IP Inventory report

---

lib/App/Netdisco/Worker/Plugin/MakeRancidConf.pm

- Add a variable to check that a device is unique in rancid exported file
- Add a default domain_suffix to avoid some warning message

Avoid duplicate device in rancid export file

---

.gitignore

wsl2 + vscode info will be coming to the wiki soon

ignore .vscode dir

---

MANIFEST.SKIP

ignore vscode dir

---

README.md

move travis from .org to .com

---

lib/App/Netdisco/Worker/Plugin/Macsuck/Nodes.pm

VLANs in the state 'suspended' cannot be polled via SNMP. While the VLAN state is suspended, the ports associated with this VLAN are shutdown, and that VLAN does not pass any traffic.
SNMP queries will result in a 'SNMP Auth Error' on the device and the polling takes longer (since Netdisco will retry the query a few times).
This pull request checks the VLAN state before macsucking and skips it if the state is 'suspended'.

Do not macsuck suspended VLANs

---

lib/App/Netdisco/Worker/Plugin/Arpnip/Nodes.pm

Fix issue #852

---

lib/App/Netdisco/Web/Plugin/Search/Device.pm

This PR add a `seeallcolumns` parameters in search device for seeing all columns from device.
Why is this useful ?
When using api, it miss some information like OS name. With this parameters all informations became available.
As I didn't wanted to break anything with webui, I've prefered to make this parameter.
I hope some others will find it useful.
BTW, thanks for this great tool

Ability to see all columns when searching device

---

share/views/ajax/device/ports.tt

match the order of the headers
could be from #902 or adding ifindex to display

fix for #930

---

lib/App/Netdisco/DB.pm

2.058000 has db schema changes but we did not update the version here

fix db schema version for 2.058000

---

lib/App/Netdisco/SSHCollector/Platform/FortiOS.pm

Update the SSH Colector for FortiOS to support the multivdom environment
By default, currently, the module think you didn't have VDOM.
With this change, the module search if you are in a VDOM context and, in this case, perform the lookup on all the context

App::Netdisco::SSHCollector::Platform::FortiOS

---

lib/App/Netdisco/SSHCollector/Platform/FortiOS.pm

@earendilfr & @ollyg - this is a slightly improved version of the FortiOS collector
* can handle --More-- pagination
* suppress some uninitialized variable warnings

FortiOS.pm improvements

---

lib/App/Netdisco/SSHCollector/Platform/NXOS.pm

NX-OS SSHCollector errors out parsing output of some IPv6 neighbor entries on old versions of NX-OS

---

bin/ieee-oui-import

ieee-oui-import also inserts ranges for randomized addresses

---

lib/App/Netdisco/SSHCollector/Platform/NXOS.pm

Add a macsuck collector function to module sshcollector::nxos

sshcollector::nxos: Add macsuck function

---

MANIFEST
META.json
META.yml
bin/netdisco-sshcollector
lib/App/Netdisco/SSHCollector/Platform/OS10.pm

Developed this for our site and am offering to contribute it upstream.

Add OS10 SSHCollector

---

lib/App/Netdisco/Transport/SNMP.pm
lib/App/Netdisco/Util/SNMP.pm
lib/App/Netdisco/Worker/Plugin/Discover/Properties.pm
lib/App/Netdisco/Worker/Plugin/Internal/SNMPFastDiscover.pm
lib/App/Netdisco/Worker/Runner.pm
share/config.yml

based on findings in https://github.com/netdisco/netdisco/issues/1141#issuecomment-3227916387

fixes for workflow errors and performance

---

share/views/sidebar/report/generic_report.tt

The change allow to create a bind_parameters like this :
```yaml
bind_params:
- param: 'comp'
default: 'lan'
type: 'list'
options:
- lan
- wan
- dc
```

Add the possiblity to use a HTML select list as bind_paramaters

---

lib/App/Netdisco/SSHCollector/Platform/EOS.pm

Created an SSHCollector for Arista EOS to work around #1396.

Arista EOS SSHCollector
