- lib/App/Netdisco/Core/Discover.pm
Hi Oliver & Netdisco Team
We encountered some devices with random non-utf8 data in syscontact and syslocation,
making the insert fail with "ERROR:  invalid byte sequence for encoding "UTF8"
on discovery. E.g. 
```
[13394] 2017-04-20 07:10:40  info discover: status error: error running job: DBIx::Class::Storage::DBI::_dbh_execute(): 
DBI Exception: DBD::Pg::st execute failed: ERROR:  invalid byte sequence for encoding "UTF8": 
0xfc [for Statement "INSERT INTO device ( contact, description, dns, fan, ip, last_discover, layers, 
location, mac, model, name, os, os_ver, ports, ps1_status, ps1_type, ps2_status, ps2_type, serial, 
slots, snmp_class, snmp_comm, snmp_ver, uptime, vendor) 
VALUES ( ?, ?, ?, ?, ?, now(), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )" 
with ParamValues: …
```
> Fix potential Postgres insert failure

- bin/netdisco-sshcollector
It is necessary to include the "Pod::Usage" module to use the "pod2usage" method. Otherwise, an error occurs if an incorrect CLI option is used.
> Missing Pod::Usage dependency

- bin/netdisco-sshcollector
While setting up an sshcollector, I found that the script doesn't handle an
arpless device very gracefully.  The log looks like:
[46567] 2018-04-10 16:59:08  warn WARNING: no entries received from <IP>
Can't use string ("1") as an ARRAY ref while "strict refs" in use at perl5/bin/netdisco-sshcollector line 114, <__ANONIO__> line 3.
This is fixed by making the process function always return the expected
structure, even if it's empty.  After this error, the following errors showed
up:
[53232] 2018-04-10 17:06:15  warn WARNING: no entries received from <IP>
[53210] 2018-04-10 17:06:15  info  [134.71.0.126] arpnip - retrieved 0 entries
Use of uninitialized value in sprintf at perl5/bin/netdisco-sshcollector line 119, <__ANONIO__> line 3.
[53210] 2018-04-10 17:06:15  info arpnip - processed …
> fix sshcollector errors when devices are empty

- bin/netdisco-sshcollector
If SSH prints anything to stderr, it leaks out to the caller of sshcollect. This change dumps it into /dev/null instead.
It might be better to collect it and output it for debug purposes, but this cleans up logging in the interim.
I'm only able to test this with the Palo Alto plugin so I apologize if it breaks one of the others.
> dump sshcollector stderr into null

- bin/netdisco-db-deploy
- bin/netdisco-do
- bin/netdisco-sshcollector
- lib/App/Netdisco.pm
remove references to ~netdisco/bin and use ~/bin instead.
2 reasons:
1) ~netdisco/ assumes you have installed netdisco under a user named "netdisco"
2) if you follow the install instructions you will have executed "chmod 600 ~/environments/deployment.yml", so commands will fail as any other user since they dont have read access on deployment.yml.
> remove reference to netdisco user in command examples.

- share/config.yml
not sure if this is a typo or not, but bri singaling interfaces have 1 'l' on cisco devices.
"BRI0-Signaling" was taken from a netdisco report, router is a "897VaK9" running ios "15.5(3)M7".
as such, i've added the 1 'l' variant to the ignore_interfaces list. if this was indeed a typo perhaps the double 'll' variant can be deleted.
> 1 more isdn interface to ignore

- lib/App/Netdisco/JobQueue.pm
- lib/App/Netdisco/JobQueue/PostgreSQL.pm
- share/config.yml
related to #466 
add an option to set the amount of jobs returned by the job queue webinterface.  when a discoverall fires off we have around 1000 jobs in the queue. the job queue webinterface does not always seem to show running or queued jobs before completed ones.
with the default of 50 sometimes we just get a list of completed jobs with no way to check (or stop/delete) if there are queued or running jobs. this adds a option in the configuration so you can increase the amount of jobs shown. i prefer 200 jobs with a refresh rate of 30 seconds.
perhaps a dropdown box based on table_showrecordsmenu would also be an option.
or a sorting preference (first running, then queued, then error, then done, etc), but then you will also need to define a maximum timeframe based on job submission. but …
> make job queue list in webinterface configurable

- lib/App/Netdisco/Worker/Plugin/Discover/Properties.pm
- share/config.yml
as #463 by nic. but now with config item to select types to filter, which can be set to [] to not filter at all.
went through my device database, seems only cisco small business switches have "notpresent" interfaces at first glance. this can be either down/notPresent or up/notPresent.
side note: really old ros versions (1.1.2.0) report port channel interfaces as ethernetCsmacd.
> ignore notpresent interfaces, with type filtering config item

- bin/netdisco-sshcollector
also,
whitespace cleanup (now passes podchecker)
openssh is also required
reference config file with F<>
in responce to #473
> correct public key documentation

- lib/App/Netdisco/Worker/Plugin/Discover/Neighbors.pm
- lib/App/Netdisco/Worker/Plugin/Discover/PortPower.pm
- lib/App/Netdisco/Worker/Plugin/Discover/PortProperties.pm
- lib/App/Netdisco/Worker/Plugin/Discover/Properties.pm
- lib/App/Netdisco/Worker/Plugin/Discover/VLANs.pm
- lib/App/Netdisco/Worker/Plugin/Discover/Wireless.pm
- lib/App/Netdisco/Worker/Plugin/Macsuck/Nodes.pm
- lib/App/Netdisco/Worker/Plugin/Nbtstat/Core.pm
2 whitespace cleanups also included, as well as rewording props -> properties like in the rest of portproperties.pm
> #479 part 2, use debug logging instead of info

- share/views/ajax/device/details.tt
since most attributes in device details alrdy have search links, why not add os as well?
> also make os a link in device details

- bin/netdisco-do
- lib/App/Netdisco/Worker/Plugin/Show.pm
had almost created an issue for this, then i thought i might as well give it a go myself. would like a few more eyes on this. perhaps it could be written more efficiently, but i find this to be quite readable.
the idea is that if you prefix -e with :: you will use plain snmp::info without more specific modules loaded.
as a bonus this also also makes this no longer fail, but more error handling could still be added.
```
netdisco-do show -d 10.40.254.65 -e ::interfaces
[18660] 2019-01-11 23:49:48  info App::Netdisco version 2.040002 loaded.
[18660] 2019-01-11 23:49:48  info show: [10.40.254.65]/::interfaces started at Sat Jan 12 00:49:48 2019
Use of uninitialized value $sub_name in string eq at /home/netdisco/perl5/lib/perl5/SNMP/Info.pm line 4986.
Use of uninitialized value $sub_name in …
```
> allow snmp::info base class in netdisco-do

- lib/App/Netdisco/Util/SNMP.pm
When we perform the reindexing for the VRF, we need to avoid to use the prefix vlan- for SNMP context.
> Fix an issue with the reindixing for VRF

- Changes
- bin/netdisco-do
- bin/netdisco-rancid-export
- bin/netdisco-sshcollector
- lib/App/Netdisco/Configuration.pm
- lib/App/Netdisco/Worker/Plugin/MakeRancidConf.pm
- share/config.yml
- share/environments/deployment.yml
* stop running bin/netdisco-rancid-export unless config use_legacy_rancidexport is set
* update makerancidconf manual a bit
* add makerancidconfig to default schedule but set to null
* 2 unrelated typo fixes
* document netdisco-do makerancidconf option
> netdisco rancid export

- lib/App/Netdisco/Worker/Plugin/Contact.pm
- lib/App/Netdisco/Worker/Plugin/Location.pm
- lib/App/Netdisco/Worker/Plugin/PortName.pm
allow setting of pseudo device port names (was added in 1f020e07ee0da9bb3a6deacbf690f0ec515d0e49 but somehow got lost?) while there, also allow setting of contact & location.
since this is done via the default job queue devices must be allowed to run actions (on by default , but see #561)
> allow setting some speudo device  info

- lib/App/Netdisco/Web/PortControl.pm
- share/public/css/netdisco.css
- share/views/ajax/admintask/nodemonitor.tt
- share/views/ajax/admintask/users.tt
- share/views/sidebar/device/netmap.tt
- share/views/sidebar/device/ports.tt
- share/views/sidebar/report/moduleinventory.tt
- share/views/sidebar/report/netbios.tt
- share/views/sidebar/report/nodesdiscovered.tt
- share/views/sidebar/report/nodevendor.tt
- share/views/sidebar/report/portssid.tt
- share/views/sidebar/search/device.tt
mostly select tags which were closed (had a / at the end) before the options were included and tt statements which were missing a space in front of their output string.
also change one use of $a to any other variable name, see https://perldoc.perl.org/perlvar.html#SPECIAL-VARIABLES for that.
finally changed 1 css attribute min-width from none to 0, none is not allowed it seems.
all of these were found with intellij idea ultimate from jetbrains: https://www.jetbrains.com/idea/
they were kind enough to validate netdisco & snmp::info as worthy open source projects, so you can get a free license for all their products, as long as you don't use it on any commercial or otherwise for profit projects.
> html template fixups

- .gitignore
- lib/App/Netdisco/Web/Plugin/Search/Node.pm
- lib/App/Netdisco/Web/Search.pm
perhaps there is a reason to use '00:00:00:00' instead of '00:00:00:00:00:00', but i can't see why, even when going through git history.
> compare ieee mac against 6 iterations

- share/public/css/netdisco.css
a4d4bf7f339ffc31bacf8359ebbbe85462984f46
"wireless access point" wraps, make sidebar 5px wider to make it not wrap
> make sidebar tiny bit wider

- lib/App/Netdisco/Worker/Plugin/Discover/Neighbors/DOCSIS.pm
- share/config.yml
Adds discovery capability of DOCSIS (Cable) modems off a headend. Uses generic DOCSIS MIBs supported in SNMP::Info.
Works with my infrastructure, but ARRIS and Motorola (and other vendor) modems may require additional MIBs or processing to correctly determine models.
> Add DOCSIS/Cable Modem Discovery

- lib/App/Netdisco/Util/PortMAC.pm
- lib/App/Netdisco/Worker/Plugin/Macsuck/Nodes.pm
From IRC today:
19:31 < rc9000> hi guys! some days ago our db cluster switched my postgres instance 
to the backup dc, but netdisco remained at the main dc.
19:31 < rc9000> a little later I got complaints that I was using about 400mbit/s of 
the already highly saturated link
19:32 < rc9000> it turns out that get_port_macs queries a full list of all device_port 
ips and macs, which is about 13MB in our case
19:33 < rc9000> and we poll 9000ish devices in 40 minutes, so the math works out :) 
19:34 < rc9000> i'm looking at the code and it seems i could make a slightly more specific 
get_port_macs inside walk_fwtable, that contains only the macs really 
returned from snmp->fw_mac
This PR tries to fix the above with a get_port_macs that's called inside walk_fwtable and only returns the macs …
> Reduce macsuck bandwidth usage to database

- lib/App/Netdisco/SSHCollector/Platform/VOSS.pm
This module works for Extreme (formerly Avaya) VSP switches running the
VOSS operating system. When using multiple VRFs, the default Arpnip does
not work.
The way to query the ARP tables of different VRFs is to append "::X" to
the end of the SNMP community string, where "X" is the VRF ID number.
Since Netdisco doesn't support querying with multiple community strings
at this time, this module uses SSH to query the ARP tables of all the
VRFs by default or select VRFs using the "vrfs" key in "device_auth"
(see documentation in the module for an example).
> new SSHCollector platform for Extreme VSP

- lib/App/Netdisco/Worker/Plugin/Discover/Neighbors.pm
Is it ok if we remove <"> from the "weird characters" in Neighbors.pm? Background is that the remote_port from Nokia TiMOS (the former Alcatel-Lucent brand devices) looks like this: 
6/2/13, 10/100/Gig Ethernet SFP, "the descrption the user entered"
Not removing the <"> makes the device_port.remote_port match the matching device_port.descr, and also makes the "Connected devices" link in the Web UI work. I found no adverse effects.
> Allow <"> in remote_port

- bin/netdisco-backend
* when rotate_logs restarts the process due to the file being
above the size limit, the new PID is not returned to the
caller
* this leads to signal_child signaling the old, non-existing PID
and subsequently a second master process being started
* fixed by returning the PID from rotate_logs
> Bugfix: after rotate_logs, restarter() may have a stale PID

- lib/App/Netdisco/Worker/Plugin/Discover/Properties.pm
Use by default the ipTable MIB entry to retrieve the IP address of interfaces and fallback to the index method as previously. 
Fixe the issue with the case where the index is not really an IP address (seen in Fortinet with VDOM).
Related to issue #1016
> Change the way to retrieve IP address of interfaces

- lib/App/Netdisco/DB.pm
- share/schema_versions/App-Netdisco-DB-78-79-PostgreSQL.sql
Hello @ollyg & team. We've put quite a bunch of additional attributes into custom_fields. Works great but got a bit slow, could we add these indexes to speed up various jsonb operations?
This requires GIN and the jsonb_ops, AFAICT this should work in 9.6 already: https://www.postgresql.org/docs/9.6/gin-builtin-opclasses.html - but I've only tried it in >= 12
> Add indexes for custom_fields in device + device_port

- lib/App/Netdisco/JobQueue/PostgreSQL.pm
Related to the incident #993
Concerning the error message `error bless( {'msg' => 'DBIx::Class::SQLMaker::ClassicExtensions::puke(): Fatal: Operator calls in update must be in the form { -op => $arg } at /home/netdisco/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 282
'}, 'DBIx::Class::Exception' )`.
I suspect that, sometime, the log is not defined and so, the function failed:
When it's work:
```
DEBUG: id=$VAR1 = 8680630;
| status=$VAR1 = 'done';
| log=$VAR1 = 'Ended macsuck for 10.208.232.13';
| started=$VAR1 = 'Fri Jun 30 15:32:32 2023';
| finished=$VAR1 = 'Fri Jun 30 15:33:28 2023';
| action=$VAR1 = 'macsuck';
| subaction=$VAR1 = '';
| only_namespace=$VAR1 = undef;
| obj=$VAR1 = {
'log' => 'Ended macsuck for 10.208.232.13',
'status' => 'done',
'finished' => 'Fri Jun 30 …
```
> Fix an error when the log string is empty

- lib/App/Netdisco/Configuration.pm
- lib/App/Netdisco/Web/Auth/Provider/DBIC.pm
This PR adds support for setting an optional timeout and adding optional Vendor-Specific Attributes (VSA) to an auth request.
For the timeout the config would look like:
```yaml
radius:
server: radius00.example.net
secret: mYsecRet
timeout: 30
```
The timeout is useful when 2FA is being used and additional time is required. The default is set to 15 sec.
For the VSAs the config would look like:
```yaml
radius:
server: radius00.example.net
secret: mYsecRet
vsa:
- name: Class
value: Netdisco
- name: 101
value: Netdisco
type: string
vendor: 123
```
Adding VSA(s) is useful to route and classify auth requests to handle differently on radius backends.
I removed the 'h323-return-code' and 'Digest-Attributes' attributes as I don't see why those are being sent other than they were in the …
> add support for custom radius VSAs for Access-Request

- lib/App/Netdisco/DB/ResultSet/Device.pm
- lib/App/Netdisco/Web/Plugin/Search/Node.pm
- lib/App/Netdisco/Web/Plugin/Search/Port.pm
- lib/App/Netdisco/Web/Search.pm
Currently, when you search a false MAC address like `e2:62:a3:31:5e:734` or `ae2:62:a3:31:5e:73`, you receive an error 500.
So, a simple fix to filter correctly when the MAC address is bad.
But, I think a better solution should be send back an error message in WebUI to indicate that the MAC address is wrong...
> Fix an issue when you try to search a false MAC

- Build.PL
- bin/netdisco-do
- lib/App/Netdisco/Web/AdminTask.pm
- lib/App/Netdisco/Worker/Plugin/PingSweep.pm
- share/config.yml
- share/views/ajax/device/addresses.tt
- share/views/index.tt
This worker is a utility which runs ping against an IP prefix and enqueues a discover job for any host that responds.
You'll need to install Net::Ping::External and have the ping utility installed on your system.
IP prefix is passed in the -p (port) parameter.
Timeout is 0.1 seconds default or pass any number to the -e (extra) parameter.
The IPs are pinged sequentially so it's as slow as num hosts x timeout. To parallelise and make things faster, queue the pingsweep job and use netdisco workers.
You could also run this as additional schedule config periodically for one or more IP prefixes.
The timeout is achieved using a signal because the timeout param to CLI ping is either integer (too slow) or root privilege or simply missing on some *nix platforms.
> ping sweep utility worker to enqueue discover jobs from an IP prefix

- lib/App/Netdisco/SSHCollector/Platform/NXOS.pm
If the cli user is set up with the predefined priviledge level 1, the `terminal length 0` command is not allowed.
We can append a `| no-more` to the commands instead which has the same effect and does not need specific rights.
fixes #1221
> use `| no-more` instead of `terminal length 0` on NXOS

- Build.PL
- lib/App/Netdisco/Configuration.pm
- lib/App/Netdisco/Transport/Python.pm
- lib/App/Netdisco/Util/Python.pm
- lib/App/Netdisco/Worker/Plugin/LoadMIBs.pm
- lib/App/Netdisco/Worker/Plugin/PythonShim.pm
- lib/App/Netdisco/Worker/Runner.pm
- share/python/netdisco/netdisco/runner.py
- share/python/netdisco/netdisco/util/database.py
- share/python/netdisco/netdisco/util/perl.py
- share/python/netdisco/netdisco/util/stash.py
- share/python/netdisco/netdisco/worklet/stats/early.py
- share/python/netdisco/pyproject.toml
this change removes three limitations:
- there is now basic database connectivity available (`from netdisco.util.database import engine`)
- one python subprocess is started (lazily) for all worklets in a job
- vars is now transferred in a temporary file so unrestricted in size (config is still transferred in environment for security)
> remove three limitations on python worklets

- share/config.yml
- share/environments/deployment.yml
- share/views/layouts/main.tt
Include an optional branding configuration option.
Adding a branding_text option to the deployment.yaml will allow customization of the header.
eg: `branding_text: Netdisco XYZ Corporate Office`
if this option is not set, it will default to "Netdisco"
> Add branding text option to web UI

- lib/App/Netdisco/SSHCollector/Platform/NXOS.pm
- lib/App/Netdisco/Transport/SSH.pm
- lib/App/Netdisco/Worker/Plugin/Arpnip/Subnets.pm
This adds a function to the NXOS SSHCollector module which retrieves subnets
by getting the routing table for all vrfs via cli and then filters for attached nets and ignoring /32.
closes #1323
> function to retrieve subnets from NXOS devices via cli
